export const allCountries = new Set([
    "Greenland",
    "Norway",
    "Canada",
    "United States of America",
    "Mexico",
    "Guatemala",
    "Belize",
    "El Salvador",
    "Honduras",
    "Nicaragua",
    "Costa Rica",
    "Panama",
    "Colombia",
    "Venezuela",
    "Ecuador",
    "Peru",
    "Bolivia",
    "Chile",
    "Paraguay",
    "Argentina",
    "Uruguay",
    "Brazil",
    "Falkland Islands",
    "Suriname",
    "Guyana",
    "French Guiana",
    "France",
    "United Kingdom",
    "Ireland",
    "Spain",
    "Portugal",
    "Switzerland",
    "Italy",
    "Austria",
    "Germany",
    "Belgium",
    "Netherlands",
    "Czech Republic",
    "Poland",
    "Slovakia",
    "Hungary",
    "Slovenia",
    "Croatia",
    "Bosnia and Herzegovina",
    "Republic of Serbia",
    "Montenegro",
    "Albania",
    "Kosovo",
    "Macedonia",
    "Greece",
    "Bulgaria",
    "Turkey",
    "Romania",
    "Ukraine",
    "Belarus",
    "Lithuania",
    "Latvia",
    "Estonia",
    "Russia",
    "Sweden",
    "Denmark",
    "Finland",
    "Moldova",
    "Georgia",
    "Armenia",
    "Azerbaijan",
    "Iran",
    "Iraq",
    "Syria",
    "West Bank",
    "Israel",
    "Jordan",
    "Lebanon",
    "Cyprus",
    "Northern Cyprus",
    "Tunisia",
    "Algeria",
    "Morocco",
    "Egypt",
    "Libya",
    "Chad",
    "Sudan",
    "Niger",
    "Mali",
    "Burkina Faso",
    "Mauritania",
    "Western Sahara",
    "Senegal",
    "Guinea",
    "Guinea Bissau",
    "Sierra Leone",
    "Liberia",
    "Ivory Coast",
    "Ghana",
    "Togo",
    "Benin",
    "Cameroon",
    "Nigeria",
    "Equatorial Guinea",
    "Gabon",
    "Republic of the Congo",
    "Central African Republic",
    "Democratic Republic of the Congo",
    "South Sudan",
    "Ethiopia",
    "Uganda",
    "Kenya",
    "United Republic of Tanzania",
    "Somalia",
    "Somaliland",
    "Djibouti",
    "Eritrea",
    "Yemen",
    "Saudi Arabia",
    "Qatar",
    "Kuwait",
    "United Arab Emirates",
    "Oman",
    "Mozambique",
    "Zambia",
    "Zimbabwe",
    "Malawi",
    "Botswana",
    "South Africa",
    "Swaziland",
    "Lesotho",
    "Namibia",
    "Angola",
    "Burundi",
    "Rwanda",
    "Madagascar",
    "The Bahamas",
    "Cuba",
    "Jamaica",
    "Haiti",
    "Dominican Republic",
    "Puerto Rico",
    "Trinidad and Tobago",
    "Antarctica",
    "Australia",
    "Indonesia",
    "Papua New Guinea",
    "Solomon Islands",
    "New Caledonia",
    "Vanuatu",
    "Fiji",
    "Philippines",
    "Malaysia",
    "Brunei",
    "Thailand",
    "Myanmar",
    "Cambodia",
    "Vietnam",
    "Laos",
    "Bangladesh",
    "India",
    "Nepal",
    "Bhutan",
    "China",
    "Kazakhstan",
    "Mongolia",
    "North Korea",
    "South Korea",
    "Taiwan",
    "Japan",
    "Sri Lanka",
    "Pakistan",
    "Afghanistan",
    "Turkmenistan",
    "Uzbekistan",
    "Tajikistan",
    "Kyrgyzstan",
    "Iceland",
    "New Zealand",
    "Luxembourg",
    "Malta",
    'French Southern and Antarctic Lands'

]);

export const exceptedCountries = new Set([
    "Western Sahara",
    'French Southern and Antarctic Lands',
    'Antarctica',
    'Vanuatu',
    "Falkland Islands",
    'New Caledonia'
]);

export const country_rename = new Map([
    ['Macedonia', 'North Macedonia'],
    ['Republic of Serbia', 'Serbia'],
    ['United Republic of Tanzania', 'Tanzania'],
    ['United Arab Emirates', 'UAE'],
    ['Swaziland', 'Eswatini']

]);